/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-06 at 20:54:36 UTC 
 * Modify at your own risk.
 */

package com.appspot.enhanced_cable_88320.aroundmeapi.model;

/**
 * Model definition for UserAroundMe.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the aroundmeapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserAroundMe extends com.google.api.client.json.GenericJson {

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String displayName;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String imageUrl;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime lastSeen;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private GeoPt location;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String mail;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getDisplayName() {
        return displayName;
    }

    /**
     * @param displayName displayName or {@code null} for none
     */
    public UserAroundMe setDisplayName(java.lang.String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getImageUrl() {
        return imageUrl;
    }

    /**
     * @param imageUrl imageUrl or {@code null} for none
     */
    public UserAroundMe setImageUrl(java.lang.String imageUrl) {
        this.imageUrl = imageUrl;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public com.google.api.client.util.DateTime getLastSeen() {
        return lastSeen;
    }

    /**
     * @param lastSeen lastSeen or {@code null} for none
     */
    public UserAroundMe setLastSeen(com.google.api.client.util.DateTime lastSeen) {
        this.lastSeen = lastSeen;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public GeoPt getLocation() {
        return location;
    }

    /**
     * @param location location or {@code null} for none
     */
    public UserAroundMe setLocation(GeoPt location) {
        this.location = location;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getMail() {
        return mail;
    }

    /**
     * @param mail mail or {@code null} for none
     */
    public UserAroundMe setMail(java.lang.String mail) {
        this.mail = mail;
        return this;
    }

    @Override
    public UserAroundMe set(String fieldName, Object value) {
        return (UserAroundMe) super.set(fieldName, value);
    }

    @Override
    public UserAroundMe clone() {
        return (UserAroundMe) super.clone();
    }

}